# Continuous Delivery Workflow
name: stg-caller-workflow
run-name: Continuous delivery triggered by ${{ github.event_name }}

on:
  # Pull Request opened on default branch
  pull_request: 
    types:
      - opened

# permissions:
#  contents: read

jobs:
  # Build static site using Reveal-MD
  build-stg:
    name: Build STG
    uses: ./.github/workflows/reuse-build-revealmd.yml
    with: 
      branch-name: ${{ github.ref_name }}
      deploy-stage: 'stg'


  # Upload testing result artifacts (maybe additional testing over CI)
  # TODO
  # PR Checks
  # TODO: CI Testing Results
  # TODO: Additional STG Testing Results
  deploy-to-github-pages:
  name: Deploy GHP(STG)
    needs: build-stg
    uses: ./.github/workflows/reuse-deploy-github-pages.yml
    with:
      branch-name: ${{ github.ref_name }}
      deploy-stage: 'stg'